name: hsbc_functional_requirements
description: ''
version: 0.0.1
author: nimbus@simpledatalabs.com
language: scala
buildSystem: maven
pipelines:
  pipelines/GeneralTests:
    name: GeneralTests
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-08-05 21:02:11'
    datasets:
      inputs:
      - 2678/datasets/tpch-customer
      - 2678/datasets/ebcdic_example
      - 2678/datasets/parquet-example
      outputs:
      - 2678/datasets/validation-rules-output
      - 2678/datasets/validated_rows
      - 2678/datasets/dedupe-first
      - 2678/datasets/dedupe-last
      - 2678/datasets/ebcdic_example
      - 2678/datasets/parquet-example
      - 2678/datasets/intersect_example
    dependencies: {}
  pipelines/scd1_merge:
    name: scd1_merge
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-08-06 00:10:56'
    datasets:
      inputs:
      - 2678/datasets/customers-raw
      - 2678/datasets/customers-scd1
      outputs:
      - 2678/datasets/customers-scd1
    dependencies: {}
  pipelines/HeadersAndFooters:
    name: HeadersAndFooters
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-08-07 22:32:30'
    datasets:
      inputs:
      - 2678/datasets/header_footer_stripped_csv
      - 2678/datasets/customers-text
      outputs:
      - 2678/datasets/concatenated_output
      - 2678/datasets/footer_line
      - 2678/datasets/header_line
    dependencies: {}
  pipelines/OperatorsAndGems:
    name: OperatorsAndGems
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-08-05 21:04:56'
    datasets:
      inputs:
      - 2678/datasets/tpch-customer
      - 2678/datasets/tpch-nation
      - 2678/datasets/tpch-part
      - 2678/datasets/tpch-orders
      outputs:
      - 2678/datasets/order-by-example
      - 2678/datasets/us-uk-union-example
      - 2678/datasets/us-uk-outer-join-example
    dependencies: {}
  pipelines/SQLOperators:
    name: SQLOperators
    description: ''
    author: nimbus@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-08-05 20:51:53'
    datasets:
      inputs:
      - 2678/datasets/tpch-customer
      outputs:
      - 2678/datasets/tpch-sql-examples
      - 2678/datasets/aggregate-examples
      - 2678/datasets/row-number-example
      - 2678/datasets/select-distinct-example
    dependencies: {}
datasets:
  datasets/order-by-example:
    name: order-by-example
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 21:20:35'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 21:20:35'
  datasets/validated_rows:
    name: validated_rows
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 22:43:51'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 22:43:51'
  datasets/dedupe-first:
    name: dedupe-first
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 22:44:54'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 22:44:54'
  datasets/us-uk-outer-join-example:
    name: us-uk-outer-join-example
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 21:45:31'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 21:45:31'
  datasets/parquet-example:
    name: parquet-example
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-06 00:04:23'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-06 00:04:23'
  datasets/row-number-example:
    name: row-number-example
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 20:57:46'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 20:57:46'
  datasets/customers-scd1:
    name: customers-scd1
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-08 03:18:11'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-08 03:18:11'
  datasets/tpch-part:
    name: tpch-part
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 21:17:29'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 21:17:29'
  datasets/tpch-nation:
    name: tpch-nation
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 21:06:06'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 21:06:06'
  datasets/customers-raw:
    name: customers-raw
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-06 00:13:38'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-06 00:13:38'
  datasets/us-uk-union-example:
    name: us-uk-union-example
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 21:42:41'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 21:42:41'
  datasets/customers-text:
    name: customers-text
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-07 23:43:02'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-07 23:43:02'
  datasets/aggregate-examples:
    name: aggregate-examples
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 20:57:16'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 20:57:16'
  datasets/dedupe-last:
    name: dedupe-last
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 22:45:39'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 22:45:39'
  datasets/concatenated_output:
    name: concatenated_output
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-07 23:11:26'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-07 23:11:26'
  datasets/validation-rules-output:
    name: validation-rules-output
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 22:42:56'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 22:42:56'
  datasets/ebcdic_example:
    name: ebcdic_example
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 23:42:01'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 23:42:01'
  datasets/intersect_example:
    name: intersect_example
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-06 00:06:05'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-06 00:06:05'
  datasets/footer_line:
    name: footer_line
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-07 22:42:57'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-07 22:42:57'
  datasets/header_line:
    name: header_line
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-07 22:42:15'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-07 22:42:15'
  datasets/header_footer_stripped_csv:
    name: header_footer_stripped_csv
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-07 23:55:26'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-07 23:55:26'
  datasets/tpch-orders:
    name: tpch-orders
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 21:30:21'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 21:30:21'
  datasets/tpch-sql-examples:
    name: tpch-sql-examples
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 20:54:44'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 20:54:44'
  datasets/tpch-customer:
    name: tpch-customer
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 20:52:38'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 20:52:38'
  datasets/select-distinct-example:
    name: select-distinct-example
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-05 20:58:18'
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-05 20:58:18'
templates: {}
jobs: {}
libraries: []
subgraphs:
  subgraphs/FilterUK_US:
    name: FilterUK_US
    description: ''
    author: nimbus@simpledatalabs.com
    language: scala
    createdAt: '2022-08-05 21:49:25'
  subgraphs/GenerateRandomIncrements:
    name: GenerateRandomIncrements
    description: ''
    author: nimbus@simpledatalabs.com
    language: scala
    createdAt: '2022-08-08 03:21:05'
dependencies: '[]'
